db:
  image: postgres:9.3
  volumes:
    - ./:/var/lib/postgresql/data/
  ports:
    - 5432
web:
  build: .
  command: bundle exec rails s
  volumes:
    - .:/usr/src/app
  ports:
    - 3000:3000
  links:
    - db
